// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Kevin Szkudlapski
// Auto-generated — do not edit

#include "vedx64/core.hpp"
#include <cstring>

namespace vedx64 {

namespace {

inline uint8_t modrm_mod(uint8_t b) { return b >> 6; }
inline uint8_t modrm_reg(uint8_t b) { return (b >> 3) & 7; }
inline uint8_t modrm_rm(uint8_t b)  { return b & 7; }

int imm_size(OpSize sz, bool op_size_override, bool rex_w) {
    switch (sz) {
    case OpSize::Byte: case OpSize::ByteSignExt: return 1;
    case OpSize::Word: return 2;
    case OpSize::Dword: return 4;
    case OpSize::Qword: return 8;
    case OpSize::OpSz: return op_size_override ? 2 : 4;
    case OpSize::OpSzQ: return rex_w ? 8 : (op_size_override ? 2 : 4);
    case OpSize::OpSzDS: return op_size_override ? 2 : 4;
    default: return 0;
    }
}

int disp_size(uint8_t modrm, bool has_sib) {
    uint8_t mod_ = modrm_mod(modrm);
    uint8_t rm = modrm_rm(modrm);
    if (mod_ == 0 && rm == 5) return 4; // RIP-relative
    if (mod_ == 0) {
        if (has_sib && (modrm_rm(modrm) == 4)) {
            // SIB with base=5 and mod=0 means disp32
            return 0; // checked via SIB below
        }
        return 0;
    }
    if (mod_ == 1) return 1;
    if (mod_ == 2) return 4;
    return 0; // mod=3, register
}

} // anonymous namespace

static bool mod_compatible(const InstrDesc& d, uint8_t modrm_mod) {
    bool is_mem = (modrm_mod != 3);
    // Entry-level mod filter: 1=mem only, -1=reg only
    if (d.mod_filter == 1 && !is_mem) return false;
    if (d.mod_filter == -1 && is_mem) return false;
    // Operand-level constraints
    for (uint8_t i = 0; i < d.num_operands; ++i) {
        if (d.operands[i].addr == AddrMode::MemOnly && !is_mem) return false;
        if ((d.operands[i].addr == AddrMode::RegOnly || d.operands[i].addr == AddrMode::XmmRegOnly || d.operands[i].addr == AddrMode::MmxRegOnly) && is_mem) return false;
    }
    return true;
}

static bool has_vex_operand(const InstrDesc& d) {
    for (uint8_t i = 0; i < d.num_operands; ++i)
        if (d.operands[i].addr == AddrMode::VexReg || d.operands[i].addr == AddrMode::XmmVvvv) return true;
    return false;
}

struct LookupEntry { uint16_t index; uint16_t opcode; uint8_t prefix; uint8_t sec_opcd; };
static constexpr uint32_t HASH_SIZE = 4096;
static constexpr uint16_t EMPTY = 0xFFFF;

// Opcode map lookup: maps[map_id][opcode_byte] → first table index, or EMPTY
// map_id: 0=1-byte, 1=0F, 2=0F38, 3=0F3A
// Generated by table.cpp alongside g_instr_table
extern uint16_t g_opcode_map[4][256];
extern uint16_t g_opcode_chain[];

static const InstrDesc* lookup(uint16_t opcode, uint8_t prefix, uint8_t modrm_reg, uint8_t sec, uint8_t modrm_mod, bool is_evex = false, bool vex_w = false, bool is_vex = false) {
    // Determine map and byte
    uint8_t map_id, byte;
    if (opcode == 0x0F38) { map_id = 2; byte = sec; }
    else if (opcode == 0x0F3A) { map_id = 3; byte = sec; }
    else if ((opcode & 0xFF00) == 0x0F00) { map_id = 1; byte = opcode & 0xFF; }
    else { map_id = 0; byte = opcode & 0xFF; }

    const InstrDesc* fallback = nullptr;
    const InstrDesc* first_match = nullptr;
    const InstrDesc* evex_match = nullptr;

    // Walk the chain for this opcode slot
    for (uint16_t idx = g_opcode_map[map_id][byte]; idx != EMPTY; idx = g_opcode_chain[idx]) {
        const auto& d = g_instr_table[idx];
        if (d.opcd_ext != 0xFF && d.opcd_ext != modrm_reg) continue;
        if (d.sec_opcd != 0xFF && d.sec_opcd != sec) continue;
        if (!mod_compatible(d, modrm_mod)) continue;
        // W-bit filter for D/Q variants
        if (d.vex_w != 0 && (is_vex || is_evex)) {
            if (d.vex_w == -1 && vex_w) continue;  // requires W=0 but got W=1
            if (d.vex_w == 1 && !vex_w) continue;  // requires W=1 but got W=0
        }
        // Skip entries that require specific prefix encoding
        const char* mn = mnemonic_name(d.mnemonic);
        if (!is_vex && !is_evex) {
            if (has_vex_operand(d)) continue;
            if (mn[0] == 'k') continue; // mask ops require VEX
            // EVEX-only unsigned converts should not match legacy encoding
            if (strncmp(mn, "vcvt", 4) == 0 && strstr(mn, "u")) continue;
        }
        // EVEX-only instructions: skip for VEX (non-EVEX) queries
        if (is_vex && !is_evex) {
            if (strncmp(mn, "vscalef", 7) == 0 || strncmp(mn, "vgetexp", 7) == 0 ||
                strncmp(mn, "vcvtps2uqq", 10) == 0 || strncmp(mn, "vcvtpd2uqq", 10) == 0 ||
                strncmp(mn, "vcvtsd2usi", 10) == 0 || strncmp(mn, "vcvtss2usi", 10) == 0 ||
                strncmp(mn, "vcvttsd2usi", 11) == 0 || strncmp(mn, "vcvttss2usi", 11) == 0 ||
                strncmp(mn, "vcvtps2udq", 10) == 0 || strncmp(mn, "vcvtpd2udq", 10) == 0 ||
                strncmp(mn, "vcvtusi", 7) == 0 || strncmp(mn, "vcvtudq", 7) == 0 ||
                strncmp(mn, "vcvtuqq", 7) == 0 || strncmp(mn, "vcvttps2uqq", 11) == 0 ||
                strncmp(mn, "vcvttpd2uqq", 11) == 0 || strncmp(mn, "vcvttps2udq", 11) == 0 ||
                strncmp(mn, "vcvttpd2udq", 11) == 0) continue;
        }
        if (d.prefix == prefix) {
            if (!first_match) first_match = &d;
            if (is_evex && has_vex_operand(d) && !evex_match) evex_match = &d;
        }
        if (d.prefix == 0 && !fallback) fallback = &d;
    }
    if (is_evex && evex_match) return evex_match;
    if (first_match) return first_match;
    if (fallback) return fallback;

    // Register-in-opcode: try base opcode (mask low 3 bits)
    if (map_id == 0 || map_id == 1) {
        uint8_t base_byte = byte & 0xF8;
        for (uint16_t idx = g_opcode_map[map_id][base_byte]; idx != EMPTY; idx = g_opcode_chain[idx]) {
            const auto& d = g_instr_table[idx];
            if (!has_opcode_reg(d)) continue;
            if (d.prefix == prefix) return &d;
            if (d.prefix == 0 && !fallback) fallback = &d;
        }
    }
    return fallback;
}

size_t decode(const uint8_t* code, size_t len, DecodedInstr& out) {
    if (!code || len == 0) return 0;
    memset(&out, 0, sizeof(out));
    size_t pos = 0;

    // Parse legacy prefixes
    uint8_t mandatory_prefix = 0;
    bool has_66 = false, has_f2 = false, has_f3 = false;
    for (;;) {
        if (pos >= len) return 0;
        uint8_t b = code[pos];
        if (b == 0xF0 || b == 0xF2 || b == 0xF3 ||
            b == 0x2E || b == 0x36 || b == 0x3E || b == 0x26 ||
            b == 0x64 || b == 0x65 || b == 0x66 || b == 0x67) {
            if (out.num_prefixes < 4) out.legacy_prefix[out.num_prefixes++] = b;
            if (b == 0x66) has_66 = true;
            if (b == 0xF2) has_f2 = true;
            if (b == 0xF3) has_f3 = true;
            ++pos;
        } else break;
    }

    // Parse EVEX / VEX prefix
    uint16_t opcode;
    uint8_t third_opcd = 0xFF;
    if (pos < len && code[pos] == 0x62) {
        // EVEX prefix: 62 [P0] [P1] [P2] opcode
        if (pos + 4 > len) return 0;
        uint8_t p0 = code[pos+1], p1 = code[pos+2], p2 = code[pos+3];
        out.has_vex = true; // treat EVEX as extended VEX for compatibility
        out.has_evex = true;
        out.evex_aaa = p2 & 0x07;       // opmask register k0-k7
        out.evex_z = (p2 >> 7) & 1;     // zeroing-masking
        out.evex_b = (p2 >> 4) & 1;     // broadcast / SAE / rounding
        out.evex_rc = (p2 >> 5) & 3;    // rounding control (L'L when evex_b && mod==11)
        uint8_t rex_bits = 0x40;
        if (!(p0 & 0x80)) rex_bits |= 0x04; // ~R → REX.R (bit 7 of P0)
        if (!(p0 & 0x40)) rex_bits |= 0x02; // ~X → REX.X (bit 6 of P0)
        if (!(p0 & 0x20)) rex_bits |= 0x01; // ~B → REX.B (bit 5 of P0)
        if (p1 & 0x80) rex_bits |= 0x08;    // W → REX.W (bit 7 of P1)
        out.rex = rex_bits;
        // R' (bit 4 of P0): extends modrm.reg to 5 bits for regs 16-31
        // Not mapped to REX — handled separately if needed for ZMM16-31
        out.vex_vvvv = (~p1 >> 3) & 0xF;
        if (!(p2 & 0x08)) out.vex_vvvv |= 0x10; // V' (bit 3 of P2, inverted) → 5th bit of vvvv
        out.vex_L = (p2 >> 5) & 3; // EVEX L'L (bits 6:5 of P2): 00=128, 01=256, 10=512
        out.vex_W = (p1 >> 7) & 1;
        uint8_t pp = p1 & 3;
        if (pp == 1) { has_66 = true; mandatory_prefix = 0x66; }
        else if (pp == 2) { has_f3 = true; mandatory_prefix = 0xF3; }
        else if (pp == 3) { has_f2 = true; mandatory_prefix = 0xF2; }
        uint8_t mmm = p0 & 0x07;
        pos += 4;
        if (pos >= len) return 0;
        if (mmm == 1) { opcode = 0x0F00 | code[pos++]; }
        else if (mmm == 2) { opcode = 0x0F38; third_opcd = code[pos++]; }
        else if (mmm == 3) { opcode = 0x0F3A; third_opcd = code[pos++]; }
        else return 0;
    } else if (pos < len && (code[pos] == 0xC5 || code[pos] == 0xC4)) {
        out.has_vex = true;
        if (code[pos] == 0xC5) {
            // 2-byte VEX: C5 [RvvvvLpp]
            if (pos + 2 > len) return 0;
            uint8_t b1 = code[pos + 1];
            out.rex = (b1 & 0x80) ? 0 : 0x44; // ~R → REX.R
            out.vex_vvvv = (~b1 >> 3) & 0xF;
            out.vex_L = (b1 >> 2) & 1;
            uint8_t pp = b1 & 3;
            if (pp == 1) { has_66 = true; mandatory_prefix = 0x66; }
            else if (pp == 2) { has_f3 = true; mandatory_prefix = 0xF3; }
            else if (pp == 3) { has_f2 = true; mandatory_prefix = 0xF2; }
            pos += 2;
            // 2-byte VEX implies 0F opcode map
            if (pos >= len) return 0;
            opcode = 0x0F00 | code[pos++];
        } else {
            // 3-byte VEX: C4 [RXBmmmmm] [WvvvvLpp]
            if (pos + 3 > len) return 0;
            uint8_t b1 = code[pos + 1], b2 = code[pos + 2];
            uint8_t rex_bits = 0x40;
            if (!(b1 & 0x80)) rex_bits |= 0x04; // ~R → REX.R
            if (!(b1 & 0x40)) rex_bits |= 0x02; // ~X → REX.X
            if (!(b1 & 0x20)) rex_bits |= 0x01; // ~B → REX.B
            if (b2 & 0x80) rex_bits |= 0x08;    // W → REX.W
            out.rex = rex_bits;
            out.vex_vvvv = (~b2 >> 3) & 0xF;
            out.vex_L = (b2 >> 2) & 1;
            out.vex_W = (b2 >> 7) & 1;
            uint8_t pp = b2 & 3;
            if (pp == 1) { has_66 = true; mandatory_prefix = 0x66; }
            else if (pp == 2) { has_f3 = true; mandatory_prefix = 0xF3; }
            else if (pp == 3) { has_f2 = true; mandatory_prefix = 0xF2; }
            uint8_t mmmmm = b1 & 0x1F;
            pos += 3;
            if (pos >= len) return 0;
            if (mmmmm == 1) { opcode = 0x0F00 | code[pos++]; }
            else if (mmmmm == 2) { opcode = 0x0F38; third_opcd = code[pos++]; }
            else if (mmmmm == 3) { opcode = 0x0F3A; third_opcd = code[pos++]; }
            else return 0; // invalid mmmmm
        }
    } else if (pos < len && code[pos] == 0xD5) {
        // REX2 prefix: D5 [M0.R4.X4.B4.W.R.X.B]
        if (pos + 1 >= len) return 0;
        uint8_t payload = code[pos+1];
        out.has_rex2 = true;
        uint8_t rex_bits = 0x40;
        if (payload & 0x04) rex_bits |= 0x04; // R
        if (payload & 0x02) rex_bits |= 0x02; // X
        if (payload & 0x01) rex_bits |= 0x01; // B
        if (payload & 0x08) rex_bits |= 0x08; // W
        out.rex = rex_bits;
        // Extended bits: R4 (bit 4 of reg), X4 (bit 4 of index), B4 (bit 4 of base/rm)
        out.rex2_r4 = (payload >> 4) & 1;
        out.rex2_x4 = (payload >> 5) & 1;
        out.rex2_b4 = (payload >> 6) & 1;
        bool m0 = (payload >> 7) & 1; // map select: 0=legacy, 1=0F
        pos += 2;
        if (pos >= len) return 0;
        if (m0) { opcode = 0x0F00 | code[pos++]; }
        else { opcode = code[pos++]; }
    } else {
        // Parse REX prefix (only if no VEX)
        if (pos < len && (code[pos] & 0xF0) == 0x40) {
            out.rex = code[pos++];
        }

        // Parse opcode
        if (pos >= len) return 0;
        if (code[pos] == 0x0F) {
            ++pos;
            if (pos >= len) return 0;
            opcode = 0x0F00 | code[pos++];
        } else {
            opcode = code[pos++];
        }

        // Three-byte opcode escape
        if (opcode == 0x0F38 || opcode == 0x0F3A) {
            if (pos >= len) return 0;
            third_opcd = code[pos++];
        }
    }
    bool rex_w = (out.rex & 0x08) != 0;

    if (!out.has_vex) {
        if (has_f2) mandatory_prefix = 0xF2;
        else if (has_f3) mandatory_prefix = 0xF3;
        else if (has_66) mandatory_prefix = 0x66;
    }

    uint8_t modrm_byte = 0, modrm_reg_val = 0, sec_byte = 0xFF;
    bool have_modrm = false;

    if (pos < len) {
        modrm_byte = code[pos];
        modrm_reg_val = modrm_reg(modrm_byte);
        // Check for secondary opcode (mod==11, full byte)
        if (modrm_mod(modrm_byte) == 3) sec_byte = modrm_byte;
    }

    uint8_t lookup_sec = (third_opcd != 0xFF) ? third_opcd : sec_byte;

    uint8_t modrm_mod_val = modrm_mod(modrm_byte);
    const InstrDesc* desc = lookup(opcode, mandatory_prefix, modrm_reg_val, lookup_sec, modrm_mod_val, out.has_evex, out.vex_W, out.has_vex);
    if (!desc) {
        // Try without secondary opcode (for two-byte opcodes)
        desc = lookup(opcode, mandatory_prefix, modrm_reg_val, 0xFF, modrm_mod_val, out.has_evex, out.vex_W, out.has_vex);
    }
    if (!desc) {
        // Try without mandatory prefix
        desc = lookup(opcode, 0, modrm_reg_val, 0xFF, modrm_mod_val, out.has_evex, out.vex_W, out.has_vex);
    }
    if (!desc) return 0;
    out.desc = desc;
    out.opcode_reg = (uint8_t)(opcode & 7);

    if (desc->has_modrm) {
        if (pos >= len) return 0;
        out.modrm = code[pos++];
        have_modrm = true;

        if (modrm_mod(out.modrm) != 3 && modrm_rm(out.modrm) == 4) {
            if (pos >= len) return 0;
            out.sib = code[pos++];
        }

        int dsize = disp_size(out.modrm, modrm_rm(out.modrm) == 4);
        // SIB base=5 with mod=0 has disp32
        if (modrm_mod(out.modrm) == 0 && modrm_rm(out.modrm) == 4 && (out.sib & 7) == 5) dsize = 4;
        if (pos + dsize > len) return 0;
        if (dsize == 1) out.displacement = (int8_t)code[pos];
        else if (dsize == 4) { int32_t v; memcpy(&v, &code[pos], 4); out.displacement = v; }
        pos += dsize;
    }

    for (uint8_t i = 0; i < desc->num_operands; ++i) {
        if (desc->operands[i].addr == AddrMode::Immediate ||
            desc->operands[i].addr == AddrMode::RelOffset) {
            int isz = imm_size(desc->operands[i].size, has_66, rex_w);
            if (pos + isz > len) return 0;
            out.immediate = 0;
            memcpy(&out.immediate, &code[pos], isz);
            // Sign-extend
            if (isz == 1) out.immediate = (int8_t)(uint8_t)out.immediate;
            else if (isz == 2) out.immediate = (int16_t)(uint16_t)out.immediate;
            else if (isz == 4) out.immediate = (int32_t)(uint32_t)out.immediate;
            pos += isz;
            break; // only one immediate per instruction
        }
    }

    for (uint8_t i = 0; i < desc->num_operands; ++i) {
        if (desc->operands[i].addr == AddrMode::Moffset) {
            if (pos + 8 > len) return 0;
            memcpy(&out.displacement, &code[pos], 8);
            pos += 8;
            break;
        }
    }

    if (opcode == 0x0F3A && out.immediate == 0) {
        bool has_imm_op = false;
        for (uint8_t i = 0; i < desc->num_operands; ++i)
            if (desc->operands[i].addr == AddrMode::Immediate) has_imm_op = true;
        if (!has_imm_op) {
            if (pos < len) out.immediate = (int8_t)code[pos++];
        }
    }

    out.length = (uint8_t)pos;
    return pos;
}

} // namespace vedx64
